import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { Exercise, MuscleGroup } from '@/lib/exercises';
import { playSfx } from './sound';


type Gender = 'male' | 'female' | '';
type ClassType = 'Novato' | 'Intermedio' | 'Pro' | '';

export interface CharacterStats {
    str: number;
    sta: number;
    will: number;
}

export interface DailyQuest {
    title: string;
    description: string[];
    xpReward: number;
}

export interface Talent {
    id: string;
    name: string;
    description: string;
    level: number;
    maxLevel: number;
    type: 'xp_boost' | 'stat_boost' | 'streak_shield';
}

export interface RoutineConfig {
    sets: number;
    reps: number;
    weight: number; // in kg
    technique: 'Normal' | 'Dropset' | 'Superset' | 'Failure';
    restTime?: number; // seconds, default 120
}

export interface RoutineItem extends Exercise {
    config: RoutineConfig;
    instanceId: string;
}

export interface Routine {
    id: string;
    name: string;
    exercises: RoutineItem[];
    lastPerformed?: string;
    isAutoGenerated?: boolean;
    requirements?: {
        level?: number;
        str?: number;
        sta?: number;
        will?: number;
    };
}

export interface ActivityLog {
    id: string;
    type: 'workout' | 'quest';
    date: string;
    title: string;
    xpEarned: number;
    exercises?: RoutineItem[];
}

export interface WeightRecord {
    date: string;
    weight: number;
}

export type DaySchedule = {
    muscles: MuscleGroup[];
    time: string;
    mode: 'solo' | 'coop';
    isActive: boolean;
};

export type WeeklyPlan = Record<string, DaySchedule>;

export interface UserState {
    name: string;
    email: string;
    password?: string; // Local password
    isAuthenticated: boolean;
    gender: Gender;
    dailyQuest: DailyQuest;
    activeRoutine: RoutineItem[];
    age: number;
    weight: number;
    height: number;
    class: ClassType;
    level: number;
    xp: number;
    maxXp: number;
    stats: CharacterStats;
    streak: number;
    lastLogin?: string;

    // History & Progression
    activityHistory: ActivityLog[];
    weightHistory: WeightRecord[];
    talents: Talent[];
    skillPoints: number;
    dungeonUnlocks: string[];
    bossKills: string[];



    // Actions
    updateProfile: (data: Partial<UserState>) => void;
    addToRoutine: (exercise: Exercise, config?: Partial<RoutineConfig>) => void;
    removeFromRoutine: (instanceId: string) => void;
    addXp: (amount: number) => void;
    checkStreak: () => void;
    logActivity: (activity: Omit<ActivityLog, 'id' | 'date'>) => void;
    updateWeight: (newWeight: number) => void;
    reorderRoutine: (fromIndex: number, toIndex: number) => void;
    updateRoutineItem: (instanceId: string, config: Partial<RoutineConfig>) => void;
    unlockTalent: (talentId: string) => void;



    // Planner & Automation
    weeklyPlan: WeeklyPlan;
    updateWeeklyPlan: (plan: WeeklyPlan) => void;
    setRoutine: (routine: RoutineItem[]) => void;
    logout: () => void;
    hardReset: () => void;
}

export const useGameStore = create<UserState>()(
    persist(
        (set, get) => ({
            name: 'Héroe',
            email: '',
            password: '',
            isAuthenticated: false,
            gender: '',
            age: 0,
            weight: 0,
            height: 0,
            class: 'Novato',
            dailyQuest: { title: 'Misión del Día', description: ['Supera tus límites'], xpReward: 100 },
            activeRoutine: [],
            level: 1,
            xp: 0,
            maxXp: 1000,
            stats: { str: 10, sta: 10, will: 10 },
            streak: 0,
            activityHistory: [],
            weightHistory: [],
            talents: [],
            skillPoints: 0,
            dungeonUnlocks: ['forge'],
            bossKills: [],


            updateProfile: (data) => set((state) => ({ ...state, ...data })),

            addToRoutine: (ex, config) => set((state) => ({
                activeRoutine: [
                    ...state.activeRoutine,
                    {
                        ...ex,
                        instanceId: Math.random().toString(36).substr(2, 9),
                        config: {
                            sets: 3,
                            reps: 12,
                            weight: 0,
                            technique: 'Normal',
                            restTime: 120,
                            ...config
                        }
                    }
                ]
            })),

            removeFromRoutine: (id) => set((state) => ({
                activeRoutine: state.activeRoutine.filter(item => item.instanceId !== id)
            })),

            addXp: (amount) => {
                const state = get();
                const newXp = state.xp + amount;
                let levelUp = false;

                // XP Curve: 1000 * Level. Simple linear scaling.
                // Level 1 -> 1000 to Lvl 2.
                // Level 2 -> 2000 to Lvl 3.
                // Total to reach Lvl 50 = Sum(1..49) * 1000 = ~1.2M. Reasonable.
                const xpNeeded = state.level * 1000;

                if (newXp >= xpNeeded) {
                    levelUp = true;
                    // Overflow XP carries over
                    const overflow = newXp - xpNeeded;

                    set({
                        level: state.level + 1,
                        xp: overflow,
                        maxXp: (state.level + 1) * 1000,
                        stats: {
                            str: state.stats.str + 2,
                            sta: state.stats.sta + 2,
                            will: state.stats.will + 2,
                        },
                        skillPoints: state.skillPoints + 1,
                    });
                    playSfx('success'); // Level Up Sound!
                } else {
                    set({ xp: newXp });
                }
            },

            checkStreak: () => {
                const state = get();
                const last = state.lastLogin;
                const today = new Date().toISOString().split('T')[0];

                if (last === today) return;

                // New Day Logic
                const newState: Partial<UserState> = { lastLogin: today };

                // Regenerate Daily Quest
                import('./game-data').then(({ QUEST_TEMPLATES }) => {
                    const randomQuest = QUEST_TEMPLATES[Math.floor(Math.random() * QUEST_TEMPLATES.length)];
                    // XP Reward scales with level: 100 + (Level * 20)
                    const scaledXp = 100 + (state.level * 20);

                    set({
                        dailyQuest: {
                            ...randomQuest,
                            xpReward: scaledXp
                        }
                    });
                });

                if (last) {
                    const lastDate = new Date(last);
                    const diffDays = Math.floor((new Date(today).getTime() - lastDate.getTime()) / (1000 * 3600 * 24));
                    if (diffDays === 1) {
                        newState.streak = state.streak + 1;
                    } else if (diffDays > 1) {
                        // Check for Streak Shield logic here if implemented later
                        newState.streak = 1;
                    }
                } else {
                    newState.streak = 1;
                }

                set(newState);
            },

            logActivity: (activity) => {
                const exercisesSnapshot = [...get().activeRoutine];
                set((state) => ({
                    activityHistory: [
                        {
                            ...activity,
                            id: Math.random().toString(36).substr(2, 9),
                            date: new Date().toISOString(),
                            exercises: exercisesSnapshot
                        },
                        ...state.activityHistory
                    ]
                }));
            },

            updateWeight: (newWeight) => set((state) => {
                const today = new Date().toISOString().split('T')[0];
                const updatedHistory = [...state.weightHistory];
                const existingIndex = updatedHistory.findIndex(r => r.date === today);

                if (existingIndex !== -1) {
                    updatedHistory[existingIndex].weight = newWeight;
                } else {
                    updatedHistory.push({ date: today, weight: newWeight });
                }

                return {
                    weight: newWeight,
                    weightHistory: updatedHistory
                };
            }),

            reorderRoutine: (fromIndex, toIndex) => set((state) => {
                const newRoutine = [...state.activeRoutine];
                const [movedItem] = newRoutine.splice(fromIndex, 1);
                newRoutine.splice(toIndex, 0, movedItem);
                return { activeRoutine: newRoutine };
            }),

            updateRoutineItem: (instanceId, config) => set((state) => ({
                activeRoutine: state.activeRoutine.map(item =>
                    item.instanceId === instanceId
                        ? { ...item, config: { ...item.config, ...config } }
                        : item
                )
            })),

            unlockTalent: (talentId) => set((state) => {
                if (state.skillPoints <= 0) return state;
                if (state.talents.some(t => t.id === talentId)) return state;
                return { skillPoints: state.skillPoints - 1 };
            }),



            weeklyPlan: {},
            updateWeeklyPlan: (plan) => set({ weeklyPlan: plan }),
            setRoutine: (routine) => set({ activeRoutine: routine }),
            logout: () => {
                set({ isAuthenticated: false });
                window.location.href = '/';
            },
            hardReset: () => {
                localStorage.removeItem('gymmo-storage');
                window.location.reload();
            },
        }),
        {
            name: 'gymmo-storage',
        }
    )
);
