import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { Exercise, MuscleGroup } from '@/lib/exercises';
import { ACHIEVEMENTS } from './achievements';
import { Friend, Guild, Message, MOCK_GUILDS } from './social';

type Gender = 'male' | 'female' | '';
type ClassType = 'Novato' | 'Intermedio' | 'Pro' | '';

export interface CharacterStats {
    str: number;
    sta: number;
    will: number;
}

export interface DailyQuest {
    title: string;
    description: string[];
    xpReward: number;
    relatedExercises?: string[];
}

export interface Talent {
    id: string;
    name: string;
    description: string;
    level: number;
    maxLevel: number;
    type: 'xp_boost' | 'stat_boost' | 'streak_shield';
}

export interface RoutineConfig {
    sets: number;
    reps: number;
    weight: number; // in kg
    restTime: number; // in seconds
    technique: 'Normal' | 'Dropset' | 'Superset' | 'Failure';
}

export interface RoutineItem extends Exercise {
    config: RoutineConfig;
    instanceId: string;
}

export interface Routine {
    id: string;
    name: string;
    exercises: RoutineItem[];
    lastPerformed?: string;
    isAutoGenerated?: boolean;
    requirements?: {
        level?: number;
        str?: number;
        sta?: number;
        will?: number;
    };
}

export interface ActivityLog {
    id: string;
    type: 'workout' | 'quest';
    date: string;
    title: string;
    xpEarned: number;
    exercises?: RoutineItem[];
}

export interface WeightRecord {
    date: string;
    weight: number;
}

export type DaySchedule = {
    muscles: MuscleGroup[];
    time: string;
    mode: 'solo' | 'coop';
    isActive: boolean;
};

export type WeeklyPlan = Record<string, DaySchedule>;

export interface UserState {
    name: string;
    email: string;
    password?: string; // Local simple auth
    isAuthenticated: boolean;
    gender: Gender;
    dailyQuest: DailyQuest | null;
    activeRoutine: RoutineItem[];
    age: number;
    weight: number;
    height: number;
    class: ClassType;
    level: number;
    xp: number;
    maxXp: number;
    stats: CharacterStats;
    streak: number;
    lastLogin?: string;

    // Feature Persistence
    dailyHydration: { water: number; protein: number; date: string };

    // History & Progression
    activityHistory: ActivityLog[];
    bossKills: string[];
    weightHistory: WeightRecord[];
    unlockedAchievementIds: string[];
    talents: Talent[];
    skillPoints: number;

    // Social
    friends: Friend[];
    guilds: Guild[];
    activeGuildId: string | null;
    socialMessages: Message[];

    // Actions
    updateProfile: (data: Partial<UserState>) => void;
    updateHydration: (type: 'water' | 'protein', change: number) => void;
    addToRoutine: (exercise: Exercise, config?: Partial<RoutineConfig>) => void;
    removeFromRoutine: (instanceId: string) => void;
    updateRoutineItem: (instanceId: string, config: Partial<RoutineConfig>) => void;
    reorderRoutine: (routine: RoutineItem[]) => void;
    addXp: (amount: number) => void;
    checkStreak: () => void;
    logActivity: (activity: Omit<ActivityLog, 'id' | 'date'>) => void;
    updateWeight: (newWeight: number) => void;
    checkAchievements: () => void;
    unlockTalent: (talentId: string) => void;

    // Social Actions
    addFriend: (friend: Friend) => void;
    removeFriend: (friendId: string) => void;
    joinGuild: (guildId: string) => void;
    createGuild: (guild: Omit<Guild, 'id' | 'totalPower' | 'members'>) => void;
    sendSocialMessage: (message: Omit<Message, 'id' | 'timestamp'>) => void;
    clearSocialMessages: (targetId: string) => void;

    // Planner & Automation
    weeklyPlan: WeeklyPlan;
    updateWeeklyPlan: (plan: WeeklyPlan) => void;
    setRoutine: (routine: RoutineItem[]) => void;
    logout: () => void;
    hardReset: () => void;
}

export const useGameStore = create<UserState>()(
    persist(
        (set, get) => ({
            name: 'Héroe',
            email: '',
            password: '',
            isAuthenticated: false,
            gender: '',
            age: 0,
            weight: 0,
            height: 0,
            class: 'Novato',
            dailyQuest: null,
            activeRoutine: [],
            level: 1,
            xp: 0,
            maxXp: 1000,
            stats: { str: 10, sta: 10, will: 10 },
            streak: 0,
            dailyHydration: { water: 0, protein: 0, date: '' },
            activityHistory: [],
            bossKills: [],
            weightHistory: [],
            unlockedAchievementIds: [],
            talents: [],
            skillPoints: 0,
            friends: [],
            guilds: [],
            activeGuildId: null,
            socialMessages: [],

            updateProfile: (data) => set((state) => ({ ...state, ...data })),

            updateHydration: (type, change) => set((state) => {
                const today = new Date().toISOString().split('T')[0];
                const current = state.dailyHydration?.date === today ? state.dailyHydration : { water: 0, protein: 0, date: today };
                return {
                    dailyHydration: {
                        ...current,
                        [type]: Math.max(0, current[type] + change),
                        date: today
                    }
                };
            }),

            addToRoutine: (ex, config) => set((state) => ({
                activeRoutine: [
                    ...state.activeRoutine,
                    {
                        ...ex,
                        instanceId: Math.random().toString(36).substr(2, 9),
                        config: {
                            sets: 3,
                            reps: 12,
                            weight: 0,
                            restTime: 120,
                            technique: 'Normal',
                            ...config
                        }
                    }
                ]
            })),

            removeFromRoutine: (id) => set((state) => ({
                activeRoutine: state.activeRoutine.filter(item => item.instanceId !== id)
            })),

            updateRoutineItem: (instanceId, config) => set((state) => ({
                activeRoutine: state.activeRoutine.map(item =>
                    item.instanceId === instanceId ? { ...item, config: { ...item.config, ...config } } : item
                )
            })),

            reorderRoutine: (newRoutine) => set({ activeRoutine: newRoutine }),

            addXp: (amount) => {
                const state = get();
                const newXp = state.xp + amount;
                let levelUp = false;
                let newState = { xp: newXp };

                if (newXp >= state.maxXp) {
                    levelUp = true;
                    newState = {
                        xp: newXp - state.maxXp,
                        level: state.level + 1,
                        maxXp: Math.floor(state.maxXp * 1.2),
                        stats: {
                            str: state.stats.str + 2,
                            sta: state.stats.sta + 2,
                            will: state.stats.will + 2,
                        },
                        skillPoints: state.skillPoints + 1,
                    } as any;
                }

                set(newState);
                get().checkAchievements();
            },

            checkStreak: () => {
                const state = get();
                const last = state.lastLogin;
                const today = new Date().toISOString().split('T')[0];
                if (last === today) return;

                if (last) {
                    const lastDate = new Date(last);
                    const diffDays = Math.floor((new Date(today).getTime() - lastDate.getTime()) / (1000 * 3600 * 24));
                    if (diffDays === 1) {
                        set({ streak: state.streak + 1, lastLogin: today });
                    } else if (diffDays > 1) {
                        set({ streak: 1, lastLogin: today });
                    }
                } else {
                    set({ streak: 1, lastLogin: today });
                }
            },

            logActivity: (activity) => {
                const exercisesSnapshot = [...get().activeRoutine];
                set((state) => ({
                    activityHistory: [
                        {
                            ...activity,
                            id: Math.random().toString(36).substr(2, 9),
                            date: new Date().toISOString(),
                            exercises: exercisesSnapshot
                        },
                        ...state.activityHistory
                    ]
                }));
                get().checkAchievements();
            },

            updateWeight: (newWeight) => set((state) => {
                const today = new Date().toISOString().split('T')[0];
                const updatedHistory = [...state.weightHistory];
                const existingIndex = updatedHistory.findIndex(r => r.date === today);

                if (existingIndex !== -1) {
                    updatedHistory[existingIndex].weight = newWeight;
                } else {
                    updatedHistory.push({ date: today, weight: newWeight });
                }

                return {
                    weight: newWeight,
                    weightHistory: updatedHistory
                };
            }),

            checkAchievements: () => {
                const state = get();
                const { activityHistory, level, stats, unlockedAchievementIds } = state;
                const newUnlocks = [...unlockedAchievementIds];
                let changed = false;

                const workoutCount = activityHistory.filter(a => a.type === 'workout').length;
                const questCount = activityHistory.filter(a => a.type === 'quest').length;

                ACHIEVEMENTS.forEach(ach => {
                    if (newUnlocks.includes(ach.id)) return;

                    let achieved = false;
                    switch (ach.requirementType) {
                        case 'workout_count': achieved = workoutCount >= ach.requirementValue; break;
                        case 'quest_count': achieved = questCount >= ach.requirementValue; break;
                        case 'level': achieved = level >= ach.requirementValue; break;
                        case 'stat_str': achieved = stats.str >= ach.requirementValue; break;
                        case 'stat_sta': achieved = stats.sta >= ach.requirementValue; break;
                        case 'stat_will': achieved = stats.will >= ach.requirementValue; break;
                    }

                    if (achieved) {
                        newUnlocks.push(ach.id);
                        changed = true;
                    }
                });

                if (changed) {
                    set({ unlockedAchievementIds: newUnlocks });
                }
            },

            unlockTalent: (talentId) => set((state) => {
                if (state.skillPoints <= 0) return state;
                if (state.talents.some(t => t.id === talentId)) return state;
                return { skillPoints: state.skillPoints - 1 };
            }),

            addFriend: (friend) => set((state) => ({
                friends: [...state.friends.filter(f => f.id !== friend.id), friend]
            })),

            removeFriend: (id) => set((state) => ({
                friends: state.friends.filter(f => f.id !== id),
                socialMessages: state.socialMessages.filter(m => m.senderId !== id)
            })),

            joinGuild: (id) => set((state) => {
                const guild = [...state.guilds, ...MOCK_GUILDS].find(g => g.id === id);
                if (guild && state.level >= guild.requiredLevel) {
                    return { activeGuildId: id };
                }
                return state;
            }),

            clearSocialMessages: (targetId) => set((state) => ({
                socialMessages: state.socialMessages.filter(m => m.senderId !== targetId)
            })),

            createGuild: (newGuild) => set((state) => {
                if (state.level < 50) return state;
                const guild: Guild = {
                    ...newGuild,
                    id: Math.random().toString(36).substr(2, 9),
                    totalPower: 0,
                    members: [{
                        id: 'me',
                        name: state.name,
                        level: state.level,
                        heroClass: state.class,
                        lastActive: new Date().toISOString(),
                        hasAura: state.streak >= 7,
                        isOnline: true,
                        role: 'leader',
                        contribution: 0
                    }]
                };
                return {
                    guilds: [...state.guilds, guild],
                    activeGuildId: guild.id
                };
            }),

            sendSocialMessage: (msg) => set((state) => ({
                socialMessages: [
                    ...state.socialMessages,
                    {
                        ...msg,
                        id: Math.random().toString(36).substr(2, 9),
                        timestamp: new Date().toISOString()
                    }
                ]
            })),

            weeklyPlan: {},
            updateWeeklyPlan: (plan) => set({ weeklyPlan: plan }),
            setRoutine: (routine) => set({ activeRoutine: routine }),
            logout: () => {
                set({ isAuthenticated: false });
                window.location.href = '/';
            },
            hardReset: () => {
                // Clear the persistence storage
                localStorage.removeItem('gymmo-storage');
                // Force a complete reload to reset all memory states and redirect to home
                window.location.href = '/';
            },
        }),
        {
            name: 'gymmo-storage',
        }
    )
);
