import { Exercise, MuscleGroup } from '@/lib/exercises';
import { Friend, Guild, Message } from '@/lib/social';

export interface ModalSlice {
    openModals: Record<string, boolean>;
    openModal: (id: string) => void;
    closeModal: (id: string) => void;
    toggleModal: (id: string) => void;
}

export type Gender = 'male' | 'female' | '';
type ClassType = 'Novato' | 'Intermedio' | 'Pro' | '';

export interface CharacterStats {
    str: number;
    sta: number;
    will: number;
}

export interface DailyQuest {
    title: string;
    description: string[];
    xpReward: number;
    relatedExercises?: string[];
}

export interface Talent {
    id: string;
    name: string;
    description: string;
    level: number;
    maxLevel: number;
    type: 'xp_boost' | 'stat_boost' | 'streak_shield';
}

export interface RoutineConfig {
    sets: number;
    reps: number;
    weight: number;
    restTime: number;
    technique: 'Normal' | 'Dropset' | 'Superset' | 'Failure';
}

export interface RoutineItem extends Exercise {
    config: RoutineConfig;
    instanceId: string;
}

export interface Routine {
    id: string;
    name: string;
    exercises: RoutineItem[];
    lastPerformed?: string;
    isAutoGenerated?: boolean;
    requirements?: {
        level?: number;
        str?: number;
        sta?: number;
        will?: number;
    };
}

export interface ActivityLog {
    id: string;
    type: 'workout' | 'quest';
    date: string;
    title: string;
    xpEarned: number;
    exercises?: RoutineItem[];
}

export interface WeightRecord {
    date: string;
    weight: number;
}

export type DaySchedule = {
    muscles: MuscleGroup[];
    time: string;
    mode: 'solo' | 'coop';
    isActive: boolean;
};

export type WeeklyPlan = Record<string, DaySchedule>;

export interface CharacterSlice {
    name: string;
    gender: Gender;
    age: number;
    weight: number;
    height: number;
    class: ClassType;
    level: number;
    xp: number;
    maxXp: number;
    stats: CharacterStats;
    streak: number;
    lastLogin?: string;
    skillPoints: number;
    talents: Talent[];
    updateProfile: (data: Partial<CharacterSlice>) => void;
    addXp: (amount: number) => void;
    checkStreak: () => void;
    unlockTalent: (talentId: string) => void;
}

export interface RoutineSlice {
    dailyQuest: DailyQuest | null;
    activeRoutine: RoutineItem[];
    weeklyPlan: WeeklyPlan;
    addToRoutine: (exercise: Exercise, config?: Partial<RoutineConfig>) => void;
    removeFromRoutine: (instanceId: string) => void;
    updateRoutineItem: (instanceId: string, config: Partial<RoutineConfig>) => void;
    reorderRoutine: (routine: RoutineItem[]) => void;
    updateWeeklyPlan: (plan: WeeklyPlan) => void;
    setRoutine: (routine: RoutineItem[]) => void;
    setDailyQuest: (quest: DailyQuest | null) => void;
}

export interface SocialSlice {
    friends: Friend[];
    guilds: Guild[];
    activeGuildId: string | null;
    socialMessages: Message[];
    addFriend: (friend: Friend) => void;
    removeFriend: (friendId: string) => void;
    joinGuild: (guildId: string) => void;
    createGuild: (guild: Omit<Guild, 'id' | 'totalPower' | 'members'>) => void;
    sendSocialMessage: (message: Omit<Message, 'id' | 'timestamp'>) => void;
    clearSocialMessages: (targetId: string) => void;
}

export interface AchievementSlice {
    activityHistory: ActivityLog[];
    bossKills: string[];
    weightHistory: WeightRecord[];
    unlockedAchievementIds: string[];
    logActivity: (activity: Omit<ActivityLog, 'id' | 'date'>) => void;
    updateWeight: (newWeight: number) => void;
    checkAchievements: () => void;
}

export interface HydrationSlice {
    dailyHydration: { water: number; protein: number; date: string };
    updateHydration: (type: 'water' | 'protein', change: number) => void;
}

export interface SettingsSlice {
    soundEnabled: boolean;
    setSoundEnabled: (enabled: boolean) => void;
    logout: () => void;
    hardReset: () => void;
}

export type UserState = CharacterSlice & RoutineSlice & SocialSlice & AchievementSlice & HydrationSlice & SettingsSlice & ModalSlice;
